{
    'name': 'NSP User',
    'summary': 'NSP master business users and friendships',
    'description': 'Master Business Identity for NSP people. RFID tag and vehicle management are added by NSP Vehicle without coupling the base user model to device data.',
    'version': '19.0.12.0.2',
    'sequence': 10,
    'author': 'BKU Team',
    'category': 'Services',
    'depends': ['base', 'nsp_core', 'mail'],
    'installable': True,
    'application': False,
    'auto_install': False,
    'data': [
        'security/ir.model.access.csv',
        'views/user_views.xml',
        'views/friendship_views.xml',
        'views/menu_views.xml',
    ],
    'license': 'LGPL-3',
}
