{
    'name': 'NSP User',
    'summary': 'NSP master business users and friendships',
    'description': 'NSP business users linked one-to-one with internal Odoo Users for Web and Mobile authentication. Access remains controlled by Odoo Groups, ACLs and Record Rules.',
    'version': '19.0.14.0.0',
    'sequence': 10,
    'author': 'BKU Team',
    'category': 'Services',
    'depends': ['base', 'nsp_core', 'mail'],
    'installable': True,
    'application': False,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
    'data': [
        'security/ir.model.access.csv',
        'views/user_views.xml',
        'views/friendship_views.xml',
        'views/menu_views.xml',
    ],
    'license': 'LGPL-3',
}
