{
    'name': 'NSP Core',
    'summary': 'Shared NSP security groups and menus',
    'description': 'Base module for Non Stop Parking. Owns shared role groups, menu roots and fresh-install access bootstrap.',
    'version': '19.0.3.1.0',
    'sequence': 5,
    'author': 'BKU Team',
    'category': 'Services',
    'depends': ['base'],
    'data': ['security/nsp_groups.xml', 'views/menu_views.xml'],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
    'post_init_hook': 'post_init_hook',
}
