{'name': 'NSP Master Gatekeeper',
 'summary': 'Cloud source of truth, published runtime snapshots and Edge result mirrors for NSP Gatekeeper',
 'description': 'Cloud-only Gatekeeper master data, topology, measurement management and business history '
                'mirrors.',
 'version': '19.0.13.44.0',
 'sequence': 20,
 'author': 'BKU Team',
 'category': 'Services',
 'depends': ['base',
             'nsp_core',
             'web',
             'bus',
             'mail',
             't4_coreapi',
             'nsp_user',
             'nsp_vehicle',
             'nsp_rfid',
             'nsp_rfid_assignment'],
 'installable': True,
 'application': True,
 'auto_install': False,
 'data': ['data/cloud_sync_api_endpoints.xml',
          'data/device_type_data.xml',
          'data/controller_heartbeat_cron.xml',
          'security/ir.model.access.csv',
          'views/controller_views.xml',
          'views/branch_views.xml',
          'views/parking_area_views.xml',
          'views/parking_lane_views.xml',
          'views/measurement_session_views.xml',
          'views/lane_setup_wizard_views.xml',
          'views/measurement_event_views.xml',
          'views/calibration_result_views.xml',
          'views/device_views.xml',
          'views/device_type_views.xml',
          'views/parking_log_views.xml',
          'views/device_whitelist_views.xml',
          'views/menu_views.xml'],
 'assets': {'web.assets_backend': [
                                   'nsp_master_gatekeeper/static/src/scss/lane_setup.scss',
                                   'nsp_master_gatekeeper/static/src/scss/device_tree_view.scss',
                                   'nsp_master_gatekeeper/static/src/xml/device_tree_view.xml',
                                   'nsp_master_gatekeeper/static/src/js/device_tree_view.js',
                                   'nsp_master_gatekeeper/static/src/xml/lane_sequence_preview.xml',
                                   'nsp_master_gatekeeper/static/src/js/lane_sequence_preview.js',
                                   'nsp_master_gatekeeper/static/src/xml/measurement_reader_dialog.xml',
            'nsp_master_gatekeeper/static/src/js/lane_calibration_form.js',
                                   'nsp_master_gatekeeper/static/src/js/parking_live_monitor.js',
                                   'nsp_master_gatekeeper/static/src/xml/parking_live_monitor.xml',
                                   'nsp_master_gatekeeper/static/src/scss/parking_live_monitor.scss',
                                   'nsp_master_gatekeeper/static/src/scss/parking_layout.scss',
                                   ]},
 'license': 'LGPL-3'}
