# -*- coding: utf-8 -*-
from odoo import api, fields, models, _
from odoo.exceptions import ValidationError
from odoo.addons.nsp_core.utils import new_management_code


VALID_DEVICE_TYPE_CODES = {"SERVER", "CONTROLLER", "RFID_READER", "ANTENNA"}
DEVICE_CODE_PREFIX = {
    "SERVER": "EDGE",
    "CONTROLLER": "CTRL",
    "RFID_READER": "DEV",
    "ANTENNA": "ANT",
}


class DeviceWhitelist(models.Model):
    """Cloud inventory of independent device identities.

    Device Whitelist answers only: which physical/runtime device exists and what
    stable code identifies it. It never stores deployment topology. Server,
    Controller, RFID Reader and Antenna are assembled only inside Reader
    Calibration or a published Parking Layout.
    """

    _name = "nsp.device.whitelist"
    _description = "NSP Device Whitelist"
    _inherit = ["image.mixin"]
    _rec_name = "display_name"
    _order = "device_type_id, technical_code, id"

    name = fields.Char(string="Device Name", readonly=True, copy=False, index=True)
    display_name = fields.Char(compute="_compute_display_name", store=True)
    active = fields.Boolean(default=True, index=True)
    device_type_id = fields.Many2one(
        "nsp.device.type", string="Device Type", required=True,
        ondelete="restrict", index=True,
    )
    device_type_code = fields.Char(
        related="device_type_id.code", string="Device Type Code",
        store=True, readonly=True,
    )
    device_type_badge = fields.Selection(
        [
            ("SERVER", "Server"),
            ("CONTROLLER", "Controller"),
            ("RFID_READER", "RFID Reader"),
            ("ANTENNA", "Antenna"),
        ],
        string="Device Type", compute="_compute_device_type_badge", readonly=True,
    )
    technical_code = fields.Char(
        string="Management Code", readonly=True, copy=False, index=True,
        help="Stable management identity generated by Cloud and used in published configuration snapshots.",
    )
    serial_number = fields.Char(
        string="Serial Number", index=True, copy=False,
        help="Required for RFID Reader; optional for Server, Controller and Antenna.",
    )

    # One-to-one technical mirrors. These records provide runtime status fields
    # and existing API model compatibility, but they remain unassigned on Cloud.
    # No parent relationship is written here.
    edge_server_id = fields.Many2one(
        "nsp.edge.server", readonly=True, copy=False, ondelete="set null", index=True,
    )
    controller_id = fields.Many2one(
        "nsp.controller", readonly=True, copy=False, ondelete="set null", index=True,
    )
    reader_id = fields.Many2one(
        "nsp.device", readonly=True, copy=False, ondelete="set null", index=True,
    )
    antenna_id = fields.Many2one(
        "nsp.device.antenna", readonly=True, copy=False, ondelete="set null", index=True,
    )

    _sql_constraints = [
        (
            "device_whitelist_technical_code_unique", "unique(technical_code)",
            "Management Code must be unique in Device Whitelist.",
        ),
        (
            "device_whitelist_serial_unique", "unique(serial_number)",
            "Serial Number must be unique in Device Whitelist.",
        ),
    ]

    @api.depends("device_type_code")
    def _compute_device_type_badge(self):
        for record in self:
            record.device_type_badge = (
                record.device_type_code
                if record.device_type_code in VALID_DEVICE_TYPE_CODES else False
            )

    @api.depends("device_type_id.name", "serial_number", "technical_code")
    def _compute_display_name(self):
        for record in self:
            identity = record.serial_number or record.technical_code or ""
            record.display_name = "%s · %s" % (
                record.device_type_id.name or _("Device"), identity,
            )

    @api.model
    def _normalize_serial(self, value):
        value = str(value or "").strip().upper()
        return value or False

    @api.model
    def _normalize_code(self, value):
        return str(value or "").strip().upper()

    @api.model
    def _type_code_from_values(self, values, record=False):
        type_id = values.get("device_type_id")
        if type_id:
            device_type = self.env["nsp.device.type"].browse(type_id).exists()
            return self._normalize_code(device_type.code if device_type else "")
        return record.device_type_code if record else ""

    @api.onchange("device_type_id")
    def _onchange_device_type_id_generate_management_code(self):
        for record in self:
            if record._origin:
                continue
            type_code = self._normalize_code(record.device_type_id.code)
            record.technical_code = (
                new_management_code(DEVICE_CODE_PREFIX[type_code])
                if type_code in VALID_DEVICE_TYPE_CODES else False
            )

    @api.model_create_multi
    def create(self, vals_list):
        prepared = []
        for source in vals_list:
            values = dict(source)
            type_code = self._type_code_from_values(values)
            if type_code not in VALID_DEVICE_TYPE_CODES:
                raise ValidationError(_("Select Server, Controller, RFID Reader or Antenna."))
            serial = self._normalize_serial(values.get("serial_number"))
            if type_code == "RFID_READER" and not serial:
                raise ValidationError(_("Serial Number is required for RFID Reader."))
            code = self._normalize_code(values.get("technical_code"))
            if not code:
                code = new_management_code(DEVICE_CODE_PREFIX[type_code])
            values.update({
                "technical_code": code,
                "serial_number": serial,
                "name": serial or code,
            })
            prepared.append(values)
        records = super().create(prepared)
        records._sync_identity_mirrors()
        return records

    def write(self, vals):
        values = dict(vals)
        values.pop("name", None)
        if "technical_code" in values:
            values["technical_code"] = self._normalize_code(values.get("technical_code"))
        if "serial_number" in values:
            values["serial_number"] = self._normalize_serial(values.get("serial_number"))

        if len(self) > 1 and ({"device_type_id", "serial_number"} & set(values)):
            for record in self:
                record.write(dict(values))
            return True

        for record in self:
            type_code = self._type_code_from_values(values, record)
            if type_code not in VALID_DEVICE_TYPE_CODES:
                raise ValidationError(_("Unsupported Device Type."))
            if "device_type_id" in values and (
                record.edge_server_id or record.controller_id or record.reader_id or record.antenna_id
            ):
                raise ValidationError(_("Device Type cannot be changed after the device identity is created."))
            serial = values.get("serial_number", record.serial_number)
            if type_code == "RFID_READER" and not self._normalize_serial(serial):
                raise ValidationError(_("Serial Number is required for RFID Reader."))
            if "serial_number" in values or "technical_code" in values:
                values["name"] = str(
                    serial or values.get("technical_code", record.technical_code) or ""
                ).strip()

        result = super().write(values)
        if not self.env.context.get("nsp_skip_identity_mirror_sync"):
            self._sync_identity_mirrors()
        return result

    @api.constrains("device_type_id", "technical_code", "serial_number")
    def _check_device_identity(self):
        for record in self:
            if record.device_type_code not in VALID_DEVICE_TYPE_CODES:
                raise ValidationError(_("Unsupported Device Type."))
            if not self._normalize_code(record.technical_code):
                raise ValidationError(_("Management Code is required."))
            if record.device_type_code == "RFID_READER" and not self._normalize_serial(record.serial_number):
                raise ValidationError(_("Serial Number is required for RFID Reader."))

    def _prepare_sync_payload(self):
        """Return identity only; topology is supplied by the published assembly."""
        self.ensure_one()
        return {
            "technical_code": self.technical_code or "",
            "name": self.name or self.technical_code or "",
            "device_type_code": self.device_type_code or "",
            "device_type_name": self.device_type_id.name or "",
            "serial_number": self.serial_number or False,
            "active": bool(self.active),
        }

    def _sync_identity_mirrors(self):
        if self.env.context.get("nsp_skip_identity_mirror_sync"):
            return True
        for record in self:
            record._sync_identity_mirror()
        return True

    def _sync_identity_mirror(self):
        self.ensure_one()
        type_code = self.device_type_code
        active = bool(self.active)
        context = dict(nsp_from_device_whitelist=True)

        if type_code == "SERVER":
            Model = self.env["nsp.edge.server"].sudo().with_context(active_test=False, **context)
            runtime = self.edge_server_id.exists() or Model.search(
                [("edge_server_code", "=", self.technical_code)], limit=1,
            )
            values = {
                "name": self.name or self.technical_code,
                "edge_server_code": self.technical_code,
                "active": active,
            }
            if not active:
                values["status"] = "revoked"
            runtime.write(values) if runtime else None
            runtime = runtime or Model.create(values)
            if runtime.whitelist_id != self:
                runtime.write({"whitelist_id": self.id})
            self.with_context(nsp_skip_identity_mirror_sync=True).write({
                "edge_server_id": runtime.id,
                "controller_id": False,
                "reader_id": False,
                "antenna_id": False,
            })
            return True

        if type_code == "CONTROLLER":
            Model = self.env["nsp.controller"].sudo().with_context(active_test=False, **context)
            runtime = self.controller_id.exists() or Model.search(
                [("controller_id", "=", self.technical_code)], limit=1,
            )
            values = {
                "controller_name": self.name or self.technical_code,
                "controller_id": self.technical_code,
                "edge_server_id": False,
                "active": active,
            }
            if not active:
                values["status"] = "revoked"
            runtime.write(values) if runtime else None
            runtime = runtime or Model.create(values)
            if runtime.whitelist_id != self:
                runtime.write({"whitelist_id": self.id})
            self.with_context(nsp_skip_identity_mirror_sync=True).write({
                "edge_server_id": False,
                "controller_id": runtime.id,
                "reader_id": False,
                "antenna_id": False,
            })
            return True

        if type_code == "RFID_READER":
            Model = self.env["nsp.device"].sudo().with_context(active_test=False, **context)
            runtime = self.reader_id.exists() or Model.search(
                [("serial_number", "=", self.serial_number)], limit=1,
            )
            values = {
                "name": self.name or self.serial_number or self.technical_code,
                "serial_number": self.serial_number,
                "device_code": self.technical_code,
                "controller_id": False,
                "active": active,
            }
            if not active:
                values["status"] = "offline"
            runtime.write(values) if runtime else None
            runtime = runtime or Model.create(values)
            if runtime.whitelist_id != self:
                runtime.write({"whitelist_id": self.id})
            self.with_context(nsp_skip_identity_mirror_sync=True).write({
                "edge_server_id": False,
                "controller_id": False,
                "reader_id": runtime.id,
                "antenna_id": False,
            })
            return True

        if type_code == "ANTENNA":
            Model = self.env["nsp.device.antenna"].sudo().with_context(active_test=False, **context)
            runtime = self.antenna_id.exists() or Model.search(
                [("technical_code", "=", self.technical_code)], limit=1,
            )
            values = {
                "technical_code": self.technical_code,
                "serial_number": self.serial_number,
                "device_id": False,
                "antenna_no": 0,
                "active": active,
            }
            runtime.write(values) if runtime else None
            runtime = runtime or Model.create(values)
            if runtime.whitelist_id != self:
                runtime.write({"whitelist_id": self.id})
            self.with_context(nsp_skip_identity_mirror_sync=True).write({
                "edge_server_id": False,
                "controller_id": False,
                "reader_id": False,
                "antenna_id": runtime.id,
            })
            return True

        return True
