{
    "name": "NSP Vehicle",
    "summary": "Vehicle master data, ownership and borrowing for NSP",
    "description": "Manage vehicles, ownership, reference data and temporary borrowing permissions.",
    "version": "19.0.19.1.0",
    "sequence": 30,
    "author": "BKU Team",
    "category": "Services",
    "depends": [
        "base",
        "nsp_core",
        "mail",
        "nsp_user",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
    "data": [
        "security/ir.model.access.csv",
        "security/nsp_vehicle_rules.xml",
        "data/vehicle_borrow_sequence.xml",
        "data/vehicle_master_data.xml",
        "views/vehicle_master_data_views.xml",
        "views/vehicle_views.xml",
        "views/user_vehicle_views.xml",
        "views/vehicle_borrow_views.xml",
    ],
    "license": "LGPL-3",
}
