{
    "name": "NSP Sync",
    "summary": "Edge reliable transport for NSP",
    "description": "Edge-only transport for Cloud authentication, snapshot pull, durable outbox push, retry, ACK tracking and idempotent delivery.",
    "version": "19.0.9.1.6",
    "sequence": 2,
    "author": "BKU Team",
    "category": "Services",
    "depends": [
        "base",
        "nsp_core",
        "t4_coreapi",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "data": [
        "data/sync_route_definitions.xml",
        "security/ir.model.access.csv",
        "views/sync_record_views.xml",
        "views/sync_auth_views.xml",
        "views/sync_job_views.xml",
        "views/menu_views.xml",
        "data/sync_job_data.xml",
    ],
    "license": "LGPL-3",
}
