{'name': 'NSP Business Gatekeeper',
 'summary': 'Edge parking business runtime and Controller integration',
 'description': 'Edge-only Gatekeeper runtime. Keeps independent Server/Controller/Reader identities, contextual Reader Ports, RFID '
                'runtime assignments, parking processing and measurement runtime.',
 'version': '19.0.10.66.0',
 'sequence': 20,
 'author': 'BKU Team',
 'category': 'Services',
 'depends': ['base',
             'nsp_core',
             'web',
             'bus',
             'mail',
             't4_coreapi',
             'nsp_user',
             'nsp_vehicle',
             'nsp_sync'],
 'installable': True,
 'application': True,
 'auto_install': False,
 'data': ['data/device_type_data.xml',
          'data/controller_heartbeat_cron.xml',
          'data/parking_detection_cron.xml',
          'data/controller_api_endpoints.xml',
          'security/ir.model.access.csv',
          'views/controller_views.xml',
          'views/parking_area_views.xml',
          'views/parking_lane_views.xml',
          'views/measurement_session_views.xml',
          'views/device_views.xml',
          'views/rfid_runtime_target_views.xml',
          'views/parking_detection_event_views.xml',
          'views/parking_log_views.xml',
          'views/menu_views.xml'],
 'assets': {'web.assets_backend': ['nsp_business_gatekeeper/static/src/scss/device_tree_view.scss',
                                   'nsp_business_gatekeeper/static/src/xml/device_tree_view.xml',
                                   'nsp_business_gatekeeper/static/src/js/device_tree_view.js',
                                   'nsp_business_gatekeeper/static/src/xml/detection_identity_field.xml',
                                   'nsp_business_gatekeeper/static/src/js/detection_identity_field.js',
                                   'nsp_business_gatekeeper/static/src/xml/lane_sequence_preview.xml',
                                   'nsp_business_gatekeeper/static/src/js/lane_sequence_preview.js',
                                   'nsp_business_gatekeeper/static/src/js/parking_live_monitor.js',
                                   'nsp_business_gatekeeper/static/src/xml/parking_live_monitor.xml',
                                   'nsp_business_gatekeeper/static/src/scss/parking_live_monitor.scss',
                                   'nsp_business_gatekeeper/static/src/scss/parking_layout.scss']},
 'license': 'LGPL-3'}
