# -*- coding: utf-8 -*-
import hashlib
from odoo import api, fields, models, _
from odoo.exceptions import ValidationError


class NspPushDevice(models.Model):
    _name = "nsp.push.device"
    _description = "NSP Push Device"
    _rec_name = "display_name"
    _order = "last_seen_at desc, id desc"

    display_name = fields.Char(compute="_compute_display_name", store=True)
    user_id = fields.Many2one("nsp.user", string="NSP User", ondelete="cascade", index=True)
    odoo_user_id = fields.Many2one("res.users", string="Odoo User", ondelete="set null", index=True)
    device_uid = fields.Char(required=True, index=True, copy=False, help="Stable ID generated by the mobile app installation.")
    platform = fields.Selection([
        ("android", "Android"),
        ("ios", "iOS"),
        ("web", "Web"),
    ], required=True, default="android", index=True)
    provider_type = fields.Selection([
        ("fcm", "FCM"),
        ("apns", "APNs"),
        ("hms", "HMS"),
        ("in_app", "In-App"),
    ], required=True, default="fcm", index=True)
    provider_id = fields.Many2one("nsp.push.provider", string="Push Provider", ondelete="set null", index=True)
    push_token = fields.Char(string="Push Token", copy=False, groups="base.group_system")
    push_token_hash = fields.Char(string="Token Hash", compute="_compute_push_token_hash", store=True, index=True)
    app_version = fields.Char()
    status = fields.Selection([
        ("active", "Active"),
        ("inactive", "Inactive"),
        ("revoked", "Revoked"),
    ], default="active", required=True, index=True)
    notification_enabled = fields.Boolean(default=True)
    registered_at = fields.Datetime(default=fields.Datetime.now, readonly=True)
    last_seen_at = fields.Datetime(index=True)
    revoked_at = fields.Datetime(readonly=True)
    note = fields.Text()

    delivery_ids = fields.One2many("nsp.push.delivery", "device_id", string="Deliveries", readonly=True)
    delivery_count = fields.Integer(compute="_compute_delivery_count")

    _sql_constraints = [
        ("device_uid_unique", "unique(device_uid)", "Mobile device UID must be unique."),
    ]

    @api.depends("user_id", "user_id.display_name", "odoo_user_id", "device_uid", "platform", "status")
    def _compute_display_name(self):
        for rec in self:
            owner = rec.user_id.display_name or rec.odoo_user_id.name or _("Unassigned")
            rec.display_name = "%s / %s / %s" % (owner, rec.platform or "-", rec.device_uid or "-")

    @api.depends("push_token")
    def _compute_push_token_hash(self):
        for rec in self:
            token = (rec.push_token or "").strip()
            rec.push_token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest() if token else False

    def _compute_delivery_count(self):
        grouped = self.env["nsp.push.delivery"].read_group([("device_id", "in", self.ids)], ["device_id"], ["device_id"])
        counts = {row["device_id"][0]: row["device_id_count"] for row in grouped if row.get("device_id")}
        for rec in self:
            rec.delivery_count = counts.get(rec.id, 0)

    @api.constrains("provider_type", "platform")
    def _check_platform_provider(self):
        for rec in self:
            if rec.platform == "ios" and rec.provider_type not in ("apns", "fcm", "in_app"):
                raise ValidationError(_("iOS devices must use APNs, FCM or In-App provider."))
            if rec.platform == "android" and rec.provider_type not in ("fcm", "hms", "in_app"):
                raise ValidationError(_("Android devices must use FCM, HMS or In-App provider."))

    @api.model
    def _default_provider(self, provider_type):
        return self.env["nsp.push.provider"].sudo().search([
            ("provider_type", "=", provider_type),
            ("active", "=", True),
            ("state", "=", "ready"),
        ], order="sequence, id", limit=1)

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get("device_uid"):
                vals["device_uid"] = str(vals["device_uid"]).strip()
            if not vals.get("provider_id") and vals.get("provider_type"):
                provider = self._default_provider(vals["provider_type"])
                if provider:
                    vals["provider_id"] = provider.id
            vals.setdefault("last_seen_at", fields.Datetime.now())
        return super().create(vals_list)

    def write(self, vals):
        vals = dict(vals)
        if vals.get("device_uid"):
            vals["device_uid"] = str(vals["device_uid"]).strip()
        if vals.get("provider_type") and not vals.get("provider_id"):
            provider = self._default_provider(vals["provider_type"])
            if provider:
                vals["provider_id"] = provider.id
        return super().write(vals)

    def action_revoke(self):
        self.write({"status": "revoked", "revoked_at": fields.Datetime.now(), "notification_enabled": False})
        return True

    def action_activate(self):
        self.write({"status": "active", "revoked_at": False, "notification_enabled": True, "last_seen_at": fields.Datetime.now()})
        return True

    @api.model
    def register_device(self, user=False, odoo_user=False, device_uid=False, platform="android", provider_type="fcm", push_token=False, app_version=False):
        if not device_uid:
            raise ValidationError(_("device_uid is required."))
        vals = {
            "user_id": user.id if user else False,
            "odoo_user_id": odoo_user.id if odoo_user else False,
            "device_uid": str(device_uid).strip(),
            "platform": platform or "android",
            "provider_type": provider_type or "fcm",
            "push_token": push_token or False,
            "app_version": app_version or False,
            "status": "active",
            "notification_enabled": True,
            "last_seen_at": fields.Datetime.now(),
            "revoked_at": False,
        }
        existing = self.sudo().search([("device_uid", "=", vals["device_uid"])], limit=1)
        if existing:
            existing.write(vals)
            return existing
        return self.sudo().create(vals)
