{
    'name': 'NSP Sync',
    'summary': 'Edge Server synchronization with NSP Cloud',
    'description': 'Configures one Cloud connection using the assigned Edge Server Code and runs supported Cloud pull/push jobs.',
    'version': '19.0.24.0.0',
    'sequence': 2,
    'author': 'BKU Team',
    'category': 'Services',
    'depends': ['base', 'nsp_core', 'mail', 't4_coreapi', 'nsp_user', 'nsp_gatekeeper', 'nsp_vehicle', 'nsp_rfid'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'data': [
        'security/ir.model.access.csv',
        'views/sync_record_views.xml',
        'views/sync_auth_views.xml',
        'views/sync_job_views.xml',
        'views/menu_views.xml',
        'data/sync_job_data.xml',
    ],
    'license': 'LGPL-3',
}
